version: '3.8'

services:
    pg_db:
      container_name: pg_db1
      image: postgres:latest
      ports:
        - 5431:5432
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: wakwaw123

